### ISSUE TITLE
Auth fail inside hub

### ISSUE THREAD

**Issue by Artanicus** [Artanicus/python-cozify#6]
This shouldn't happen inside hub, should get escalated to cloud and either succeed or fail there.

Traceback (most recent call last):
  File "/srv/ephemeral/cozify-temp.git/cozify-single-sample.py", line 20, in <module>
    main()
  File "/srv/ephemeral/cozify-temp.git/cozify-single-sample.py", line 9, in main
    data = hub.getDevices()
  File "/usr/local/lib/python3.5/dist-packages/cozify/hub.py", line 31, in getDevices
    raise APIError(response.status_code, response.text)
cozify.Error.APIError: API error, 401: Authentication failed.

**Comment by Artanicus** [comment]
Thinking more about this, it's actually the naive implementation in cozify-single-sample.py and cozify-sample-loop.py that is to blame. The hub interface tries to be as lean as possible so it only triggers auth if it can easily be determined it is absolutely needed, for example if there is no token at all to use. In any case the v0.2.5 branch adds in more tools to take better care to keep the connection alive and happy. Eventually this may become more automated in v0.3 since it rewrites large chunks of the hub.
